sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!--more-->"

title: "Jaiden's Portfolio & Blog" 
author: "Jaiden Gerig"

twitter:
  username: jaideng123
  card: summary

logo: assets/images/headshot.jpg
image: assets/images/headshot.jpg

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

social:
  name: Jaiden Gerig
  links:
    - https://bsky.app/profile/jaideng123.bsky.social
    - https://github.com/jaideng123
    - https://www.linkedin.com/in/jaiden-gerig-01708180/
    - https://twitter.com/JaidenG123
    - https://mastodon.gamedev.place/@JaidenG123


permalink: pretty

feed:
  categories:
    - blog

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
